server:
  type: user-control-server
  registerDefaultExceptionMappers: false
  rootPath: /api/
  requestLog:
    type: classic
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: ./logs/Request.log
        threshold: INFO
        archivedLogFilenamePattern: ./logs/Request-%d-%i.log
        maxFileSize: 1GB
        timeZone: UTC
        logFormat: "%-5level [%date{ISO8601}] %-4relative %mdc %logger - %msg%n"
  applicationConnectors:
    - type: http
      port: 1310
      maxRequestHeaderSize: 8KiB
    #- type: internalhttps
    #  port: 9220
    #  bindHost: 127.0.0.1 # only bind to loopback
    #  maxRequestHeaderSize: 8 KiB
    #  keyStorePassword: password
    #  keyStorePath: "./KeyStore.jks"
  adminConnectors:
    - type: http
      port: 1311

logging:
  level: INFO
  loggers:
    org.ghost-studios: DEBUG
    org.pac4j: WARN
    org.pac4j.http.client.direct.HeaderClient: WARN
    org.pac4j.core.profile.ProfileHelper: WARN
  appenders:
    - type: console
      threshold: INFO
      timeZone: UTC
      logFormat: "%-5level [%date{ISO8601}] %-4relative %mdc %logger - %msg%n"
    - type: file
      currentLogFilename: ./logs/usercontrol.log
      threshold: INFO
      archivedLogFilenamePattern: ./logs/usercontrol-%d-%i.log
      maxFileSize: 1GB
      timeZone: UTC
      logFormat: "%-5level [%date{ISO8601}] %-4relative %mdc %logger - %msg%n"

# A list of origins for which cross-origin requests are allowed.An origin of * allows any origin
allowedOrigins: "*"

# The Access-Control-Allow-Headers response header is used in response to a preflight request which includes the
# Access-Control-Request-Headers to indicate which HTTP headers can be used during the actual request.
allowedHeaders: "X-Requested-With,Content-Type,Accept,Origin,Authorization,Cache-Control,Content-Disposition"

# The Access-Control-Allow-Methods response header specifies the method or methods allowed when accessing the resource in response to a preflight request.
allowedMethods: "OPTIONS,GET,PUT,POST,DELETE,HEAD"

exposedHeaders: "Content-Disposition"

# Path to service configuration files. Each of these are mapped to a corresponding POJO
configPath: ./config

auth: basic

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: bookshelf

  # the password
  password: 1.327*10^-11

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/bookshelf

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time a connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute
